site_name: GO Vast client
site_url: ""
site_dir: mkdocs_files
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: index.md
  - Supported Resources: resources.md
  - For Developers: for-developers.md

plugins:
  - search
  - section-index

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
